// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1nSFQeiSNnMvqao_0m7gsrtZo1fS8Nc',
    appId: '1:636025368798:web:91575e8ac0dd51a055924f',
    messagingSenderId: '636025368798',
    projectId: 'fir-auth-ea07f',
    authDomain: 'fir-auth-ea07f.firebaseapp.com',
    storageBucket: 'fir-auth-ea07f.firebasestorage.app',
    measurementId: 'G-KBV5VDSFWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC93HurLczhvo5M4rdq0yOxxhhh5QMjyPQ',
    appId: '1:636025368798:android:3b269c6e70fa33cd55924f',
    messagingSenderId: '636025368798',
    projectId: 'fir-auth-ea07f',
    storageBucket: 'fir-auth-ea07f.firebasestorage.app',
  );
}
